include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enable additional rules
    - prefer_single_quotes
    - avoid_print
    - unnecessary_const
    - unnecessary_new
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - sort_child_properties_last
    - use_build_context_synchronously

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"